spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/pasetodb
    username: root
    password:
    driver-class-name: org.mariadb.jdbc.Driver
    hikari:
      poolName: Hikari
      auto-commit: false
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MariaDBDialect
  sql.init.mode: always