server:
  tomcat:
    access-log-enabled: true

spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/javatechie
    username: root
    password:
    driverClassName: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
      use-new-id-generator-mappings: true
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    database-platform: org.hibernate.dialect.MariaDB103Dialect
