spring:
  application:
    name: USER-AUTH-SERVICE
    client:
      origin_local_server: http://localhost/
      origin_local: http://localhost:4200/
  config:
    import: "optional:configserver:http://localhost:8000"

